# news_service.py
# Feeds the Telegram bot's news/calendar data. Reused from the web
# dashboard's Phase 3.2 news module, with one deliberate change: every
# AI/Claude-based piece has been removed (per the bot's file plan -
# "AI অংশ ছাড়া"). That means:
#   - the old _classify_and_summarize() used to call Claude for a short
#     structured read of each plain RSS headline (sentiment/impact/coin);
#     it's now a fully deterministic fallback with no network/API call.
#   - the old standalone "AI-generated market report" feature (its own
#     ANTHROPIC_API_KEY-gated function + route) has been dropped
#     entirely - the bot only needs the raw feed, not a written report.
# This file makes zero calls to Claude or any other LLM. The only
# optional external key left is ALPHA_VANTAGE_API_KEY (see source #4
# below), which is unrelated - that's Alpha Vantage's own NLP sentiment
# output, not anything generated by this project.
#
# =====================================================================
# DATA SOURCES - what was actually verified, and how
# =====================================================================
# Every URL below was checked by actually fetching it (not guessed from
# memory) before writing any parsing code against it.
#
# 1. CRYPTO NEWS - CoinDesk + Cointelegraph, both genuine official RSS
#    feeds, no key/signup required:
#      https://www.coindesk.com/arc/outboundfeeds/rss/
#      https://cointelegraph.com/rss
#
# 2. FOREX / GENERAL MARKET NEWS - FXStreet's official RSS feed, also
#    keyless:
#      https://www.fxstreet.com/news/feed
#
# 3. FOREXFACTORY ECONOMIC CALENDAR - IMPORTANT, per the task's explicit
#    instruction to not silently fake this: ForexFactory has NO official
#    public API. Every "ForexFactory API" sold on RapidAPI/Apify/etc. is
#    an unofficial third-party scraper wrapper, and ForexFactory's own
#    forum confirms this directly. What DOES genuinely exist, is free,
#    and needs no key is the JSON export ForexFactory's own CDN serves
#    for embeddable calendar widgets:
#      https://nfs.faireconomy.media/ff_calendar_thisweek.json
#    This was fetched and confirmed working - real fields are exactly
#    title/country/date/impact/forecast/previous (no "actual" value in
#    the weekly feed - FF only exposes that on the full site). This is
#    still NOT an official/documented/stable API - as of Aug 2024 FF
#    started rate-limiting it to ~2 requests/5 minutes per public
#    reports, so this module caches it hard (30 min) and degrades to
#    "no calendar data right now" rather than crashing if it's ever
#    blocked or changes shape.
#
# 4. GENERAL MARKET SENTIMENT - Alpha Vantage's NEWS_SENTIMENT endpoint,
#    OPTIONAL. Needs a free key from
#    https://www.alphavantage.co/support/#api-key. As of this writing
#    Alpha Vantage's free tier is only 25 requests/DAY (cut down from a
#    much larger allowance previously) - so this is fetched at most once
#    an hour and cached hard. If ALPHA_VANTAGE_API_KEY isn't set in the
#    environment, this source is silently skipped and everything else
#    (crypto/forex RSS + the FF calendar) still works fine.
#
# =====================================================================
# WHAT'S REAL DATA VS ESTIMATED - each item is tagged so the bot can be
# honest about this instead of presenting a guess as a fact:
#   - ForexFactory's impact rating (High/Medium/Low/Holiday) is FF's own
#     label - impact_is_estimated=False.
#   - Alpha Vantage's sentiment score is Alpha Vantage's own NLP output -
#     sentiment_is_estimated=False.
#   - Plain RSS headlines (CoinDesk/Cointelegraph/FXStreet) have no
#     native impact/sentiment/summary field at all. With the AI
#     classifier removed, these are always reported as sentiment/impact
#     "unknown" (see _classify_and_summarize) rather than a guessed
#     label - estimated=True marks that honestly instead of hiding it.

import os
import re
import json
import time
import logging
import calendar

import feedparser

from .http_client import http_session as _http_session

log = logging.getLogger("crypto-analyzer-http")

COINDESK_RSS_URL = "https://www.coindesk.com/arc/outboundfeeds/rss/"
COINTELEGRAPH_RSS_URL = "https://cointelegraph.com/rss"
FXSTREET_RSS_URL = "https://www.fxstreet.com/news/feed"
FF_CALENDAR_URL = "https://nfs.faireconomy.media/ff_calendar_thisweek.json"
ALPHA_VANTAGE_URL = "https://www.alphavantage.co/query"

# A normal browser User-Agent - some of these feeds (FF's CDN especially)
# are known to reject bare/empty user agents.
_HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; crypto-analyzer-dashboard/1.0)"}

RSS_CACHE_TTL_SECONDS = 600            # 10 min - headlines don't need per-second freshness
FF_CALENDAR_CACHE_TTL_SECONDS = 1800   # 30 min - well under FF's ~2-req/5-min limit
ALPHA_VANTAGE_CACHE_TTL_SECONDS = 3600  # 1 hour -> max 24 calls/day, under the 25/day free cap
COMBINED_FEED_CACHE_TTL_SECONDS = 120  # cheap to recompute (just merges already-cached sources)

_rss_cache = {}                 # url -> {"entries": [...], "ts": float}
_ff_calendar_cache = {"events": None, "ts": 0.0}
_av_cache = {"articles": None, "ts": 0.0}
_combined_cache = {"items": None, "ts": 0.0}
_ai_classification_cache = {}   # article url -> classification dict (never expires - a published headline doesn't change)

_TAG_RE = re.compile(r"<[^>]+>")


def _strip_html(text):
    if not text:
        return ""
    return _TAG_RE.sub(" ", text).replace("&nbsp;", " ").strip()


def _entry_timestamp(entry):
    """Best-effort epoch seconds from a feedparser entry, or None."""
    for key in ("published_parsed", "updated_parsed"):
        val = entry.get(key)
        if val:
            try:
                return calendar.timegm(val)
            except (TypeError, ValueError):
                continue
    return None


# ---------------------------------------------------------------------
# RSS sources (CoinDesk, Cointelegraph, FXStreet)
# ---------------------------------------------------------------------

def _fetch_rss(url, source_name, max_items=20):
    cached = _rss_cache.get(url)
    now = time.time()
    if cached and (now - cached["ts"]) < RSS_CACHE_TTL_SECONDS:
        return cached["entries"]

    try:
        resp = _http_session.get(url, timeout=10, headers=_HEADERS)
        resp.raise_for_status()
        parsed = feedparser.parse(resp.content)
        entries = []
        for e in parsed.entries[:max_items]:
            link = e.get("link", "")
            if not link or not e.get("title"):
                continue
            entries.append({
                "source": source_name,
                "headline": e.get("title", "").strip(),
                "url": link,
                "published_at": _entry_timestamp(e),
                "raw_summary": _strip_html(e.get("summary", ""))[:500],
            })
        _rss_cache[url] = {"entries": entries, "ts": now}
        return entries
    except Exception as ex:
        log.error(f"News: RSS fetch failed for {source_name} ({url}): {ex}")
        return cached["entries"] if cached else []


def fetch_crypto_headlines():
    return (
        _fetch_rss(COINDESK_RSS_URL, "CoinDesk")
        + _fetch_rss(COINTELEGRAPH_RSS_URL, "Cointelegraph")
    )


def fetch_forex_headlines():
    return _fetch_rss(FXSTREET_RSS_URL, "FXStreet")


# ---------------------------------------------------------------------
# ForexFactory economic calendar (unofficial community feed - see notice
# at the top of this file)
# ---------------------------------------------------------------------

def fetch_ff_calendar():
    now = time.time()
    if _ff_calendar_cache["events"] is not None and (now - _ff_calendar_cache["ts"]) < FF_CALENDAR_CACHE_TTL_SECONDS:
        return _ff_calendar_cache["events"]

    try:
        resp = _http_session.get(FF_CALENDAR_URL, timeout=10, headers=_HEADERS)
        resp.raise_for_status()
        raw = resp.json()
        events = []
        for e in raw:
            title = (e.get("title") or "").strip()
            if not title:
                continue
            events.append({
                "headline": title,
                "currency": e.get("country", ""),
                "impact": (e.get("impact") or "Low").strip(),
                "event_time_iso": e.get("date"),  # ISO8601 string, FF's own timezone offset
                "event_time": _iso_to_epoch(e.get("date")),
                "forecast": e.get("forecast", ""),
                "previous": e.get("previous", ""),
            })
        _ff_calendar_cache["events"] = events
        _ff_calendar_cache["ts"] = now
        return events
    except Exception as ex:
        # Unofficial feed - can legitimately get rate-limited or blocked.
        # Serve stale cache if we have it, otherwise an empty list (never crash).
        log.error(f"News: ForexFactory calendar fetch failed (unofficial feed, may be rate-limited): {ex}")
        return _ff_calendar_cache["events"] or []


def _iso_to_epoch(iso_str):
    if not iso_str:
        return None
    try:
        import datetime
        dt = datetime.datetime.fromisoformat(iso_str)
        return int(dt.timestamp())
    except (ValueError, TypeError):
        return None


# ---------------------------------------------------------------------
# Alpha Vantage NEWS_SENTIMENT (optional - real sentiment, needs a key)
# ---------------------------------------------------------------------

def fetch_alpha_vantage_news(max_items=20):
    api_key = os.environ.get("ALPHA_VANTAGE_API_KEY")
    if not api_key:
        log.debug("News: ALPHA_VANTAGE_API_KEY not set - skipping general-market sentiment source")
        return []

    now = time.time()
    if _av_cache["articles"] is not None and (now - _av_cache["ts"]) < ALPHA_VANTAGE_CACHE_TTL_SECONDS:
        return _av_cache["articles"]

    try:
        resp = _http_session.get(
            ALPHA_VANTAGE_URL,
            params={
                "function": "NEWS_SENTIMENT",
                "topics": "forex,blockchain,economy_macro,financial_markets",
                "apikey": api_key,
            },
            timeout=15,
        )
        resp.raise_for_status()
        data = resp.json()
        if "Information" in data or "Note" in data:
            # Alpha Vantage returns HTTP 200 with a message body when the
            # daily quota is used up, rather than a real error status.
            log.warning(f"News: Alpha Vantage returned no data (likely daily quota used up): {data.get('Information') or data.get('Note')}")
            return _av_cache["articles"] or []

        sentiment_map = {
            "Bullish": "bullish", "Somewhat-Bullish": "bullish",
            "Neutral": "neutral",
            "Somewhat-Bearish": "bearish", "Bearish": "bearish",
        }
        articles = []
        for item in data.get("feed", [])[:max_items]:
            articles.append({
                "source": item.get("source", "Alpha Vantage"),
                "headline": item.get("title", ""),
                "url": item.get("url", ""),
                "published_at": _av_time_to_epoch(item.get("time_published")),
                "raw_summary": (item.get("summary", "") or "")[:400],
                "sentiment": sentiment_map.get(item.get("overall_sentiment_label"), "neutral"),
            })
        _av_cache["articles"] = articles
        _av_cache["ts"] = now
        return articles
    except Exception as ex:
        log.error(f"News: Alpha Vantage fetch failed: {ex}")
        return _av_cache["articles"] or []


def _av_time_to_epoch(raw):
    # Alpha Vantage format: "20260715T103000"
    if not raw:
        return None
    try:
        import datetime
        dt = datetime.datetime.strptime(raw, "%Y%m%dT%H%M%S")
        return calendar.timegm(dt.timetuple())
    except (ValueError, TypeError):
        return None


# ---------------------------------------------------------------------
# Plain (non-AI) classification for RSS items that don't natively carry
# impact/sentiment/currency tags. This project intentionally does NOT
# call any AI/LLM here - everything below is a deterministic, static
# fallback so news classification stays free, key-less, and instant.
# ---------------------------------------------------------------------


def _classify_and_summarize(item):
    """
    Returns {summary, sentiment, impact, currency_or_coin, estimated}
    for a plain RSS item. No AI involved - sentiment/impact/coin are
    always "unknown"/"" since we have no reliable non-AI way to infer
    them from a bare headline, and a guessed label would be worse than
    an honest "unknown". Cached forever per article URL.
    """
    cached = _ai_classification_cache.get(item["url"])
    if cached:
        return cached

    result = {
        "summary": item.get("raw_summary", "")[:200] or item["headline"],
        "sentiment": "unknown",
        "impact": "unknown",
        "currency_or_coin": "",
        "estimated": True,
    }
    _ai_classification_cache[item["url"]] = result
    return result


# ---------------------------------------------------------------------
# Combined feed - what the /api/news route actually returns
# ---------------------------------------------------------------------

def get_news_feed(limit=60):
    now = time.time()
    if _combined_cache["items"] is not None and (now - _combined_cache["ts"]) < COMBINED_FEED_CACHE_TTL_SECONDS:
        return _combined_cache["items"][:limit]

    items = []

    for entry in fetch_crypto_headlines():
        cls = _classify_and_summarize(entry)
        items.append({
            "id": entry["url"],
            "category": "crypto",
            "source": entry["source"],
            "headline": entry["headline"],
            "url": entry["url"],
            "published_at": entry["published_at"],
            "currency_or_coin": cls["currency_or_coin"],
            "impact": cls["impact"],
            "impact_is_estimated": True,
            "sentiment": cls["sentiment"],
            "sentiment_is_estimated": True,
            "summary": cls["summary"],
        })

    for entry in fetch_forex_headlines():
        cls = _classify_and_summarize(entry)
        items.append({
            "id": entry["url"],
            "category": "forex",
            "source": entry["source"],
            "headline": entry["headline"],
            "url": entry["url"],
            "published_at": entry["published_at"],
            "currency_or_coin": cls["currency_or_coin"],
            "impact": cls["impact"],
            "impact_is_estimated": True,
            "sentiment": cls["sentiment"],
            "sentiment_is_estimated": True,
            "summary": cls["summary"],
        })

    for entry in fetch_alpha_vantage_news():
        items.append({
            "id": entry["url"],
            "category": "general",
            "source": entry["source"],
            "headline": entry["headline"],
            "url": entry["url"],
            "published_at": entry["published_at"],
            "currency_or_coin": "",
            "impact": "medium",         # Alpha Vantage doesn't rate impact - neutral default, not invented urgency
            "impact_is_estimated": True,
            "sentiment": entry["sentiment"],
            "sentiment_is_estimated": False,  # real Alpha Vantage NLP output
            "summary": entry["raw_summary"][:220],
        })

    for e in fetch_ff_calendar():
        items.append({
            "id": f"ff::{e['headline']}::{e['event_time_iso']}",
            "category": "calendar",
            "source": "ForexFactory (community calendar feed)",
            "headline": e["headline"],
            "url": "https://www.forexfactory.com/calendar",
            "published_at": e["event_time"],
            "currency_or_coin": e["currency"],
            "impact": e["impact"].lower(),
            "impact_is_estimated": False,  # ForexFactory's own official rating
            "sentiment": "neutral",        # a calendar entry is an announcement, not an analysis - no invented direction
            "sentiment_is_estimated": False,
            "summary": f"Forecast: {e['forecast'] or 'n/a'} · Previous: {e['previous'] or 'n/a'}",
        })

    items.sort(key=lambda x: x.get("published_at") or 0, reverse=True)
    _combined_cache["items"] = items
    _combined_cache["ts"] = now
    return items[:limit]